### ISSUE TITLE
这个软件要怎么用

### ISSUE THREAD

**Issue by Yoiiiii** [hongfeiyucode/ChangeIP#1]

**Comment by hongfeiyucode** [comment]
这个程序的对象是需要经常固定ip的人，比如校园网内
原来固定ip需要打开一堆窗口，自动获取IP的话又很慢
而且宿舍和教室两个地方网段不一样
使用这个程序将宿舍网段和教室网段写死在程序里面
每次只需要在最后的1~255选一个即可

**Comment by hongfeiyucode** [comment]
不过我写成随机了，就是随机获取一个IP，然后固定
这样的话就不用输入了

**Comment by Yoiiiii** [comment]
能发个给我用下吗  看能不能修改的

**Comment by hongfeiyucode** [comment]
classroom.py里面29行写的是 
`arrIPAddresses = ['10.104.111.'+str(ip_last)]`
直接改成你所在的网段即可，因为教室的网段是固定的

dormitory.py里面

```
if isjiaban=='y' or isjiaban=='Y' :
    ip_3nd='161'
else :
    ip_3nd='160'
```

因为我们宿舍两个不同的地方是两个不同的网段
所以这里有个判断，然后IP的前两段是固定好的
`arrIPAddresses = ['10.104.'+ip_3nd+'.'+str(ip_last)]`
把IP改成你在的网段

查看IP是`ipconfig`
下载的话直接下载不就行了吗，项目右上角有个download看见没
然后安装python环境，直接`python classroom.py`就行了
要是还不会我就没办法了
